apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: myactors
spec:
  serviceName: myactors
  replicas: 2
  template:
    metadata:
      labels:
        app: myactors
    spec:
      containers:
      - name: myactors
        image: localhost:32000/myactors
        ports:
        - name: http
          containerPort: 2080
